### PR TITLE
Update main.lua

### PR DESCRIPTION
**Pull request by Heady20006**
fixed the duplication-bug

### CODE REVIEW

**Comment by HumanTree92** [comment]
R u sure this is it. B/c i just tried this and i can still dupe cars from the impound.

**Comment by Heady20006** [comment]
On my server it works.
We add the spawned vehicle to a table and check if this vehicle is already in the table. 

Actually im not at home. Later i will test it again with this Code (I've already edited my Code to change the policepound to a place where the police can impound cars from other player)

**Comment by Heady20006** [comment]
I tried everything to dupe cars... But it doesnt work with my script. Is your Server with whitelist? Maybe you can give me your IP adress that we can check if its a clientside issue or serverside

**Comment by HumanTree92** [comment]
My Servers ip is 192.151.157.170:30120
You could also compare ur version vs the new one i put out to see if its the similar.

**Comment by Dhannyjsb** [comment]
I'm using this PR, and I can still dupe cars from impound.

**Comment by HumanTree92** [comment]
Closing since this didn't fix it.

**Pull request closed without merging**
